//window.sr = ScrollReveal({ duration: 2000 });
//sr.reveal('#head', 70);
//sr.reveal('.hero', 70);
//sr.reveal('.about', 50);
//sr.reveal('p', 50);
//sr.reveal('.icon', 50);
//sr.reveal('.nope');
//sr.reveal('#header-skills', 50);
//sr.reveal('#portfoliero', 50);
//sr.reveal('#project', 50);
//sr.reveal('#footer-container', 50);
//ScrollReveal().reveal('#head', {delay: 150});
//ScrollReveal().reveal('.about', { delay: 150});
//ScrollReveal().reveal('.icon', { delay: 150});
//ScrollReveal().reveal('.nope', { delay: 150});
//ScrollReveal().reveal('#header-skills', { delay: 150});
//ScrollReveal().reveal('#portfoliero', { delay: 150});
//ScrollReveal().reveal('#project', { delay: 150});
ScrollReveal().reveal('.container', { delay: 150});
ScrollReveal().reveal('.container-fluid', { delay: 150});